# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master
- release

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.Full.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  mdixColorsVersion: '2.0.0'
  mdixMahAppsVersion: '0.1.6'
  mdixVersion: '4.0.0'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.0'
    vsVersion: '16.8.0'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.100-rc.2.20479.15'
    vsVersion: '16.8.0'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'
    arguments: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU" /p:MDIXVersion=$(mdixVersion).$(Build.BuildID) /p:MDIXColorsVersion=$(mdixColorsVersion).$(Build.BuildID) /p:MDIXMahAppsVersion=$(mdixMahappsVersion).$(Build.BuildID)'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'UI Tests'
  inputs:
    command: test
    projects: '**/*.UITests'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: PublishPipelineArtifact@1
  name: "PublishUITestsScreenshots"
  inputs:
    artifact: 'Screenshots'
    targetPath: 'MaterialDesignThemes.UITests/bin/$(buildConfiguration)/netcoreapp3.1/Screenshots'
    publishLocation: 'pipeline'
  condition: always()

- task: PowerShell@2
  displayName: "Build NuGets"
  inputs: 
    filePath: 'Scripts\\BuildNugets.ps1'
    arguments: '-MDIXVersion $(mdixVersion)-ci$(Build.BuildId) -MDIXMahAppsVersion $(mdixMahappsVersion)-ci$(Build.BuildId) -MDIXColorsVersion $(mdixColorsVersion)-ci$(Build.BuildId)'

- task: PublishPipelineArtifact@1
  name: "PublishDemoApp"
  inputs:
    artifact: 'DemoApp'
    targetPath: 'MainDemo.Wpf/bin/$(buildConfiguration)'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  name: "PublishMaterialDesign"
  inputs:
    artifact: 'MDIX'
    targetPath: 'MaterialDesignThemes.$(mdixVersion)-ci$(Build.BuildId).nupkg'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  name: "PublishMaterialDesignColors"
  inputs:
    artifact: 'MDIX.Colors'
    targetPath: 'MaterialDesignColors.$(mdixColorsVersion)-ci$(Build.BuildId).nupkg'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  name: "PublishMaterialDesignMahApps"
  inputs:
    artifact: 'MDIX.MahApps'
    targetPath: 'MaterialDesignThemes.MahApps.$(mdixMahappsVersion)-ci$(Build.BuildId).nupkg'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  name: "PublishScript"
  inputs:
    artifact: 'Script'
    targetPath: 'Scripts\\UpdateNugets.ps1'
    publishLocation: 'pipeline'